### ISSUE TITLE
YML 숨기기 성공!

### ISSUE THREAD

**Issue by taesung320** [redmushroom-in-subong/server#20]
기존에 있는 yml 하고 충돌날 수도 있으니까 새로 clone 받아서 
README.MD 에 필독 들어가서 사용법 숙지해주세요 ^-^

**Comment by lse99** [comment]
넹~~

**Comment by pjoon357** [comment]
해결이 잘 되어서 다행입니다. 앞으로는 이런 상황 발생하지 않도록 조심해주세요^^
