### ISSUE TITLE
디비 비번 변경함

### ISSUE THREAD

**Issue by taesung320** [redmushroom-in-subong/server#22]
사유는 옛날에 강의 들을 때 만들었다가 지운 properties 파일에 대한 기록이 잘 안지워짐
server_secret_info  update 받으면 뭔지 나옵니다

**Comment by lse99** [comment]
Where is server_secret_info ?

**Comment by lse99** [comment]
ah man got it
I found it

**Comment by pjoon357** [comment]
지울 수 없어 비밀번호를 바꿔야 하는 방법이라니,,,,, 스윗하지 않은 방식이지만 그래도 해결되서 다행이네요^^
